# Generated by Django 5.1 on 2024-08-31 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0002_remove_reviewrating_customer'),
        ('reservation', '0005_flightfaremap_booked_seats'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewrating',
            name='customer',
            field=models.ForeignKey(default=16, on_delete=django.db.models.deletion.CASCADE, to='reservation.customerdetails'),
            preserve_default=False,
        ),
    ]
