# Generated by Django 5.1 on 2024-08-31 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0003_reviewrating_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewrating',
            name='customer',
        ),
        migrations.AddField(
            model_name='reviewrating',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
