# Generated by Django 5.1.1 on 2024-09-03 17:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AerodrumMaster',
            fields=[
                ('aerodrum_id', models.AutoField(primary_key=True, serialize=False)),
                ('aerodrum_name', models.CharField(max_length=40)),
                ('city', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ClassMaster',
            fields=[
                ('class_id', models.AutoField(primary_key=True, serialize=False)),
                ('class_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyMaster',
            fields=[
                ('company_id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='DayMaster',
            fields=[
                ('day_id', models.AutoField(primary_key=True, serialize=False)),
                ('day_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='FlightMaster',
            fields=[
                ('flight_no', models.AutoField(primary_key=True, serialize=False)),
                ('flight_name', models.CharField(max_length=30)),
                ('departure_time', models.TimeField()),
                ('arrival_time', models.TimeField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservation.companymaster')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_flights', to='reservation.aerodrummaster')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_flights', to='reservation.aerodrummaster')),
            ],
        ),
        migrations.CreateModel(
            name='FlightFareMap',
            fields=[
                ('ff_id', models.AutoField(primary_key=True, serialize=False)),
                ('no_of_seats', models.IntegerField()),
                ('booked_seats', models.JSONField(default=list)),
                ('fare', models.IntegerField()),
                ('flight_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservation.classmaster')),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservation.flightmaster')),
            ],
        ),
        migrations.CreateModel(
            name='FlightDayMap',
            fields=[
                ('fd_id', models.AutoField(primary_key=True, serialize=False)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservation.daymaster')),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservation.flightmaster')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(max_length=100)),
                ('payment_method', models.CharField(max_length=100)),
                ('amount_paid', models.FloatField()),
                ('status', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_token', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('passport_id', models.CharField(max_length=30)),
                ('customer_name', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=30)),
                ('email_id', models.CharField(max_length=30)),
                ('contact_no', models.CharField(max_length=20)),
                ('booking_date', models.DateField()),
                ('country', models.CharField(max_length=50)),
                ('fare_total', models.FloatField()),
                ('total', models.FloatField()),
                ('tax', models.FloatField()),
                ('status', models.CharField(choices=[('Cancel', 'Cancel'), ('Completed', 'Completed'), ('Pending', 'Pending')], default='Pending', max_length=10)),
                ('is_reserved', models.BooleanField(default=False)),
                ('pnr_number', models.CharField(default='', max_length=20, unique=True)),
                ('seat_number', models.CharField(max_length=10)),
                ('flight_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservation.classmaster')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservation.flightmaster')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reservation.payment')),
            ],
        ),
    ]
