# Generated by Django 5.1 on 2024-08-30 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerdetails',
            name='total',
            field=models.FloatField(default=100),
            preserve_default=False,
        ),
    ]
