# Generated by Django 5.1 on 2024-08-31 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0004_customerdetails_seat_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightfaremap',
            name='booked_seats',
            field=models.JSONField(default=list),
        ),
    ]
